### ISSUE TITLE
Error: failed to find libmagic

### ISSUE THREAD

**Issue by quicoli** [anthonyharrison/sbom4files#2] opened 2023-07-18 14:43 UTC
Hi,

python: version 3.11.3
o/s: Windows 10

I installed the sbom4files as instructions. Tried to run it and received the following error:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\sbom4files.exe\__main__.py", line 4, in <module>
  File "\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sbom4files\cli.py", line 16, in <module>
    from sbom4files.filescanner import FileScanner
  File "\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sbom4files\filescanner.py", line 7, in <module>
    import magic
  File "\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\magic\__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
               ^^^^^^^^^^^^^^^^^
  File "\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\magic\loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

**Comment by anthonyharrison** [comment] 2023-07-24 17:28
Fixed in version 0.3.0

**Closed as completed by anthonyharrison** 2023-07-24 17:28 UTC

**Comment by sajeenth** [comment] 2023-08-10 14:12
I'm having the same issue right now.

`raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation`

**Comment by anthonyharrison** [comment] 2023-08-10 20:41
Thanks for the feedback.

I can now reproduce the issue within a python virtual environment.

It would appear that there is a clash between the python-magic library
(used by Linux systems) and python-magic-bin which is used by Windows. Both
get installed on Windows which is not required.

Uninstalling python-magic allowed the program to run (sbom4files --help)
but when I tried to create an SBOM I got another error.

I will look into this later but can you provide details of your environment
and confirm your version of python and the installed modules (pip list will
be ideal).

**Comment by anthonyharrison** [comment] 2023-08-14 08:10
This issue highlights the problem and potential temporary workaround https://github.com/ahupp/python-magic/issues/248

**Comment by anthonyharrison** [comment] 2023-08-14 08:25
Try the following workaround (seems to be related to some dependency order issues)

`pip uninstall python-magic`
`pip uninstall python-magic-bin`

`pip install python-magic`
`pip install python-magic-bin`
